name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install yarn
        run: npm install --global yarn

      - name: Build backend
        run: cd backend && yarn install && yarn build

      - name: Build frontend
        run: cd rfotoprint && yarn install && yarn build-linux

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.REMOTE_SERVER }}
          port: ${{ secrets.REMOTE_PORT }}
          username: ${{ secrets.REMOTE_USERNAME }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          local-dir: ${{ secrets.LOCAL_DIRECTIORY }}
          server-dir: ${{ secrets.REMOTE_DIRECTORY }}
