name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install yarn
        run: npm install --global yarn

      - name: Build backend
        run: cd backend && yarn install && yarn build

      - name: Build frontend
        run: cd rfotoprint && yarn install && yarn build-linux

      - name: List files
        run: ls

      # - name: Sync files
      #   uses: SamKirkland/FTP-Deploy-Action@3.1.1
      #   with:
      #     ftp-server: ${{ secrets.REMOTE_SERVER }}
      #     ftp-username: ${{ secrets.REMOTE_USERNAME }}
      #     ftp-password: ${{ secrets.REMOTE_PASSWORD }}
      #     local-dir: ${{ secrets.LOCAL_DIRECTIORY }}
      #     git-ftp-args: --insecure
