name: Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install yarn
        run: npm install --global yarn

      - name: Install dependencies
        run: yarn install --production

      - name: Build backend
        run: cd backend && yarn build

      - name: Build frontend
        run: cd ../frontend && yarn build && cd ..

      # - name: Deploy to Server
      #   uses: easingthemes/ssh-deploy@main
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
      #     ARGS: "-rltgoDzvO --delete"
      #     SOURCE: "build/"
      #     REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      #     REMOTE_USER: ${{ secrets.REMOTE_USER }}
      #     TARGET: ${{ secrets.REMOTE_TARGET }}
      #     EXCLUDE: "/dist/, /node_modules/"
